/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-11-21 05:54:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mid.bean.blogBean;
import java.sql.*;
import mid.term.CommonDb;
import java.sql.*;
import java.util.*;

public final class personal_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/include.jsp", Long.valueOf(1511087567869L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mid.bean.blogBean");
    _jspx_imports_classes.add("mid.term.CommonDb");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>我的主页</title>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap-theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap-theme.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-3.2.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/user.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../editormd/examples/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../editormd/css/editormd.preview.css\" />\r\n");
      out.write("<script src=\"../editormd/examples/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/marked.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/prettify.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/raphael.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/underscore.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/sequence-diagram.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/flowchart.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/lib/jquery.flowchart.min.js\"></script>\r\n");
      out.write("<script src=\"../editormd/editormd.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

blogBean blogs = new blogBean();
ResultSet rs = blogs.getBlogs((String)(session.getAttribute("user_name")));
rs.last();
int n = rs.getRow();
String[] title = new String[n];
int[] id = new int[n];
int i = 0;
rs.first();
try {
	do{
		title[i] = rs.getString("title");
		id[i] = rs.getInt("id");
		//out.print(title[i]);
		i++;
	}while(rs.next());
}catch(SQLException e) {
	e.printStackTrace();
}

      out.write("\r\n");
      out.write("<div class='headstyle'>\r\n");
      out.write("<img src=\"../images/luntan.jpg\" width=\"30px\" height=\"30px\" style='float:left'/>\r\n");
      out.write("<div style='float:left' class='titlestyle'>在线Java技术论坛</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class='nav1'>\r\n");
      out.write("  <ul>\r\n");
      out.write("    <li><a href='home.jsp'>主页</a></li>\r\n");
      out.write("    <li ><a href='write_blog.jsp?type=1'>写博客</a>\r\n");
      out.write("     <ul>\r\n");
      out.write("      <li><a href='#'>未完待续</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class='lamp'><span></span></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div class='bodystyle'>\r\n");
      out.write("  <div class='bodystyle1'>\r\n");
      out.write("    <div>\r\n");
      out.write("       <img src=\"../images/luntan.jpg\" width=\"100px\" height=\"100px\" style='float:left'/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style='float:left'>\r\n");
      out.write("       <ul>\r\n");
      out.write("         <li><h3>");
      out.print( session.getAttribute("user_name") );
      out.write("</h3></li>\r\n");
      out.write("         <li>");
      out.print( session.getAttribute("user_email") );
      out.write("</li>\r\n");
      out.write("       </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class='bodystyle2'>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  <ul class=\"nav nav-tabs\">\r\n");
      out.write("    <!-- <li class=\"active\"><a data-toggle=\"tab\" href=\"#menu1\">写博客</a></li>  -->\r\n");
      out.write("    <li class=\"active\"><a data-toggle=\"tab\" onclick=\"show_blogs()\">我的博客</a></li>\r\n");
      out.write("    <li><a data-toggle=\"tab\">我的个人信息</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"tab-content\">\r\n");
      out.write("    <div id=\"menu1\" style=\"text-align: left; padding: 10px 20px;\">\r\n");
      out.write("      ");

      	for(int j = 0; j < n; j++) {
      		
      out.write("\r\n");
      out.write("      \t\t<p>\r\n");
      out.write("      \t\t<form action=\"show_blog.jsp\" method=\"POST\">\r\n");
      out.write("      \t\t<input style=\"display: none;\" name=\"author\" value=\"");
      out.print( session.getAttribute("user_name") );
      out.write("\">\r\n");
      out.write("      \t\t<input style=\"display: none;\" name=\"blog_id\" value=\"");
      out.print( id[j] );
      out.write("\">\r\n");
      out.write("      \t\t<input class=\"btn btn-link\" style=\"border: none;\" type=\"submit\" value=\"");
      out.print( title[j] );
      out.write("\">\r\n");
      out.write("      \t\t<a style=\"height: 35px; line-height: 35px;\" href='write_blog.jsp?type=2&blog_id=");
      out.print( id[j] );
      out.write("'>修改</a>\r\n");
      out.write("      \t\t</form>\r\n");
      out.write("      \t\t</p>\r\n");
      out.write("      \t\t");

      	}
      
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"menu2\" style=\"display: none;\">\r\n");
      out.write("      <h3>我的个人信息</h3>\r\n");
      out.write("      <p>哦哦哦</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("function show_blogs() {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
